---

- name: Setup official docker repository
  copy:
    src=docker.repo
    dest=/etc/yum.repos.d/docker.repo
    owner=root
    group=root
    mode=0644

- name: Install docker packages
  yum:
    name=docker-engine
    state=present

- name: Ensure systemd docker.service.d is present
  file:
    path=/etc/systemd/system/docker.service.d/
    state=directory
    owner=root
    group=root
    mode=644

- name: Override systemd service
  copy:
    src=override.conf
    dest=/etc/systemd/system/docker.service.d/override.conf
    owner=root
    group=root
    mode=0644
  notify:
    - reload systemd
    - restart docker

- name: Configure docker networking options
  copy:
    src=docker-network
    dest=/etc/sysconfig/docker-storage
    owner=root
    group=root
    mode=0644
  notify:
    - restart docker

- name: Ensure docker is started and enabled
  service:
    name=docker
    state=started
    enabled=true