---

- name: prepare k8s folders
  file:
    path="{{ k8s_folder }}"
    state=directory
    owner=root
    group=k8s
    mode=0750

- name: Install common sofware
  yum:
    name="{{item}}"
    state=present
  with_items:
    - python-setuptools


- name: Install pip package through easy_install
  easy_install:
    name=pip
    state=present