---

- name: Create a group for k8s
  group:
    name=k8s
    state=present
    system=yes

- name: Create system k8s user
  user:
    name=k8s
    comment="Kubernetes user"
    shell=/sbin/nologin
    state=present
    home=/var/run/k8s
    createhome=true
    system=yes
    groups=k8s