---

- name: Install etcd
  yum:
    name=etcd
    state=present

- name: Add etcd user to k8s group
  user:
    name=etcd
    groups=k8s
    append=yes

- name: Configure etcd
  template:
    src=etcd.conf.j2
    dest=/etc/etcd/etcd.conf
  notify: restart etcd

- name: Ensure etcd is started and enabled
  service:
    name=etcd
    state=started
    enabled=true

- name: Install python etcd tools
  pip: name="{{ item }}"
  with_items:
    - python-etcd

- name: Install profile script for easier etcd access
  template:
    src=etcd.sh.j2
    dest=/etc/profile.d/etcd.sh
    mode=775
    owner=root
    group=root