---

- name: create the flannel etcd config
  etcd:
    state=present
    host=127.0.0.1
    port=2379
    protocol=https
    ssl_cert="/etc/etcd/{{ ansible_fqdn }}.crt"
    ssl_key="/etc/etcd/{{ ansible_fqdn }}.key"
    key="{{ k8s_flannel_etcd_prefix }}/{{ item.key }}"
    value="{{ item.value }}"
  with_items:
    - key: Network
      value: "{{ k8s_flannel_network }}"
    - key: SubnetLen
      value: "{{ k8s_flannel_subnetlen }}"
    - key: SubnetMin
      value: "{{ k8s_flannel_subnetmin }}"
    - key: SubnetMax
      value: "{{ k8s_flannel_subnetmax }}"
  run_once: true


- name: create the flannel etcd config (vxlan backends)
  etcd:
      state=present
      host=127.0.0.1
      port=2379
      protocol=https
      ssl_cert="/etc/etcd/{{ ansible_fqdn }}.crt"
      ssl_key="/etc/etcd/{{ ansible_fqdn }}.key"
      key="{{ k8s_flannel_etcd_prefix }}/Backend/{{ item.key }}"
      value="{{ item.value }}"
  with_items:
    - key: Type
      value: vxlan
    - key: VNI
      value: "{{ k8s_flannel_backend_vxlan_vni }}"
  run_once: true
  when: k8s_flannel_backend_type == "vxlan"

