---

- name: Build the ssl cn prefix
  set_fact:
    k8s_ca_subj: "/C={{k8s_ca_country}}/ST={{k8s_ca_state}}/L={{k8s_ca_location}}/O={{k8s_ca_organization}}/OU={{k8s_ca_ou}}"

- include: create_ca.yml

- include: create_certs.yml